wget https://www.casio880.com/programas_880/Ordenacion_urbana/PROYTXUL.FX -O Ordenacion_urbana/PROYTXUL.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/ACCESIBI.FX -O Ordenacion_urbana/ACCESIBI.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/ACC-LOC2.FX -O Ordenacion_urbana/ACC-LOC2.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/ALTERNA.FX -O Ordenacion_urbana/ALTERNA.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/DEMOGRAF.FX -O Ordenacion_urbana/DEMOGRAF.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/HIDRICQA.FX -O Ordenacion_urbana/HIDRICQA.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/IN-OUT.FX -O Ordenacion_urbana/IN-OUT.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/IN-OUTPU.FX -O Ordenacion_urbana/IN-OUTPU.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/LOCA-ESP.FX -O Ordenacion_urbana/LOCA-ESP.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/LOC-EQUI.FX -O Ordenacion_urbana/LOC-EQUI.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/LOCESPE.FX -O Ordenacion_urbana/LOCESPE.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/LOGIST.FX -O Ordenacion_urbana/LOGIST.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/LOGOS.FX -O Ordenacion_urbana/LOGOS.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/MIGRAC.FX -O Ordenacion_urbana/MIGRAC.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/MIGRTXUL.FX -O Ordenacion_urbana/MIGRTXUL.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/NELSON.FX -O Ordenacion_urbana/NELSON.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/ODR-1.FX -O Ordenacion_urbana/ODR-1.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/ODR-4.FX -O Ordenacion_urbana/ODR-4.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/ODR-5.FX -O Ordenacion_urbana/ODR-5.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/ODR-6.FX -O Ordenacion_urbana/ODR-6.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana/PAISAJE.FX -O Ordenacion_urbana/PAISAJE.FX
