wget https://www.casio880.com/programas_880/algebra/ALG-CAL.FX -O algebra/ALG-CAL.FX
wget https://www.casio880.com/programas_880/algebra/ASISTENT.FX -O algebra/ASISTENT.FX
wget https://www.casio880.com/programas_880/algebra/AUTOVAL.FX -O algebra/AUTOVAL.FX
wget https://www.casio880.com/programas_880/algebra/BOLZANO.FX -O algebra/BOLZANO.FX
wget https://www.casio880.com/programas_880/algebra/CRAMER.FX -O algebra/CRAMER.FX
wget https://www.casio880.com/programas_880/algebra/DE-COM2.FX -O algebra/DE-COM2.FX
wget https://www.casio880.com/programas_880/algebra/DETERM.FX -O algebra/DETERM.FX
wget https://www.casio880.com/programas_880/algebra/DETERMIN.FX -O algebra/DETERMIN.FX
wget https://www.casio880.com/programas_880/algebra/DIVSINT.FX -O algebra/DIVSINT.FX
wget https://www.casio880.com/programas_880/algebra/EC-COMPL.FX -O algebra/EC-COMPL.FX
wget https://www.casio880.com/programas_880/algebra/ECUACION.FX -O algebra/ECUACION.FX
wget https://www.casio880.com/programas_880/algebra/ECUCOMP.FX -O algebra/ECUCOMP.FX
wget https://www.casio880.com/programas_880/algebra/ECU-DIF.FX -O algebra/ECU-DIF.FX
wget https://www.casio880.com/programas_880/algebra/ELIMGAUS.FX -O algebra/ELIMGAUS.FX
wget https://www.casio880.com/programas_880/algebra/FACTO-LU.FX -O algebra/FACTO-LU.FX
wget https://www.casio880.com/programas_880/algebra/FIS-1-1.FX -O algebra/FIS-1-1.FX
wget https://www.casio880.com/programas_880/algebra/FRACCION.FX -O algebra/FRACCION.FX
wget https://www.casio880.com/programas_880/algebra/MATRIZ.FX -O algebra/MATRIZ.FX
wget https://www.casio880.com/programas_880/algebra/MATSISTJ.FX -O algebra/MATSISTJ.FX
wget https://www.casio880.com/programas_880/algebra/MMATH.FX -O algebra/MMATH.FX
wget https://www.casio880.com/programas_880/algebra/MODULO.FX -O algebra/MODULO.FX
wget https://www.casio880.com/programas_880/algebra/POT-MATR.FX -O algebra/POT-MATR.FX
wget https://www.casio880.com/programas_880/algebra/RAICES.FX -O algebra/RAICES.FX
wget https://www.casio880.com/programas_880/algebra/RAIZPOLI.fx -O algebra/RAIZPOLI.fx
wget https://www.casio880.com/programas_880/algebra/SIS-COMP.FX -O algebra/SIS-COMP.FX
wget https://www.casio880.com/programas_880/algebra/SIS-ECU.FX -O algebra/SIS-ECU.FX
wget https://www.casio880.com/programas_880/algebra/SIS-GAUS.FX -O algebra/SIS-GAUS.FX
wget https://www.casio880.com/programas_880/algebra/SISLINE.FX -O algebra/SISLINE.FX
wget https://www.casio880.com/programas_880/algebra/sistecuacNxN.fx -O algebra/sistecuacNxN.fx
wget https://www.casio880.com/programas_880/algebra/TABLA.FX -O algebra/TABLA.FX
wget https://www.casio880.com/programas_880/astronomia/ANTONIO2.FX -O astronomia/ANTONIO2.FX
wget https://www.casio880.com/programas_880/astronomia/ASTR.FX -O astronomia/ASTR.FX
wget https://www.casio880.com/programas_880/astronomia/ASTRO.FX -O astronomia/ASTRO.FX
wget https://www.casio880.com/programas_880/astronomia/ASTRO12.FX -O astronomia/ASTRO12.FX
wget https://www.casio880.com/programas_880/astronomia/EXAMEN.FX -O astronomia/EXAMEN.FX
wget https://www.casio880.com/programas_880/calculo/CONICAS.FX -O calculo/CONICAS.FX
wget https://www.casio880.com/programas_880/calculo/DERIVAR.FX -O calculo/DERIVAR.FX
wget https://www.casio880.com/programas_880/calculo/FRACCION.FX -O calculo/FRACCION.FX
wget https://www.casio880.com/programas_880/calculo/INTEGRA.FX -O calculo/INTEGRA.FX
wget https://www.casio880.com/programas_880/calculo/INTEGRAL.FX -O calculo/INTEGRAL.FX
wget https://www.casio880.com/programas_880/calculo/MATRICES.FX -O calculo/MATRICES.FX
wget https://www.casio880.com/programas_880/calculo/POLIMAT.FX -O calculo/POLIMAT.FX
wget https://www.casio880.com/programas_880/calculo/POLINOMY.FX -O calculo/POLINOMY.FX
wget https://www.casio880.com/programas_880/calculo/RECTAS.FX -O calculo/RECTAS.FX
wget https://www.casio880.com/programas_880/calculo/TRAPECIO.FX -O calculo/TRAPECIO.FX
wget https://www.casio880.com/programas_880/cemento/DOSI-P1.FX -O cemento/DOSI-P1.FX
wget https://www.casio880.com/programas_880/cemento/DOSI-P2.FX -O cemento/DOSI-P2.FX
wget https://www.casio880.com/programas_880/cemento/MGRANUL.FX -O cemento/MGRANUL.FX
wget https://www.casio880.com/programas_880/cemento/TAMANO.FX -O cemento/TAMANO.FX
wget https://www.casio880.com/programas_880/cemento/CEMENTOS.FX -O cemento/CEMENTOS.FX
wget https://www.casio880.com/programas_880/cemento/DOSI-P0.FX -O cemento/DOSI-P0.FX
wget https://www.casio880.com/programas_880/electricidad/CALCULO-DE-A-Y-B.fx -O electricidad/CALCULO-DE-A-Y-B.fx
wget https://www.casio880.com/programas_880/electricidad/REGULACION-DEL-ANGULO-DE-DESFASE.fx -O electricidad/REGULACION-DEL-ANGULO-DE-DESFASE.fx
wget https://www.casio880.com/programas_880/electricidad/CAMBIO-ESTR-TRIANG.fx -O electricidad/CAMBIO-ESTR-TRIANG.fx
wget https://www.casio880.com/programas_880/electronica/TRANS-4R.FX -O electronica/TRANS-4R.FX
wget https://www.casio880.com/programas_880/electronica/RESIST.FX -O electronica/RESIST.FX
wget https://www.casio880.com/programas_880/electronica/Electrot.fx -O electronica/Electrot.fx
wget https://www.casio880.com/programas_880/electronica/filtros.zip -O electronica/filtros.zip
wget https://www.casio880.com/programas_880/EstadIstica/SHAP&WIL.FX -O EstadIstica/SHAP&WIL.FX
wget https://www.casio880.com/programas_880/EstadIstica/ANOVA.FX -O EstadIstica/ANOVA.FX
wget https://www.casio880.com/programas_880/EstadIstica/DBINOMIA.FX -O EstadIstica/DBINOMIA.FX
wget https://www.casio880.com/programas_880/EstadIstica/DISENO23.FX -O EstadIstica/DISENO23.FX
wget https://www.casio880.com/programas_880/EstadIstica/DISTFREC.FX -O EstadIstica/DISTFREC.FX
wget https://www.casio880.com/programas_880/EstadIstica/FAC2FIJ.FX -O EstadIstica/FAC2FIJ.FX
wget https://www.casio880.com/programas_880/EstadIstica/GCONTROL.FX -O EstadIstica/GCONTROL.FX
wget https://www.casio880.com/programas_880/EstadIstica/K-S.FX -O EstadIstica/K-S.FX
wget https://www.casio880.com/programas_880/EstadIstica/MAYWAY1.FX -O EstadIstica/MAYWAY1.FX
wget https://www.casio880.com/programas_880/EstadIstica/POISSON.FX -O EstadIstica/POISSON.FX
wget https://www.casio880.com/programas_880/Estructuras/TRANSFE.FX -O Estructuras/TRANSFE.FX
wget https://www.casio880.com/programas_880/Estructuras/VIGAS-FL.FX -O Estructuras/VIGAS-FL.FX
wget https://www.casio880.com/programas_880/Estructuras/ARTICULA.FX -O Estructuras/ARTICULA.FX
wget https://www.casio880.com/programas_880/Estructuras/ARTIESPA.FX -O Estructuras/ARTIESPA.FX
wget https://www.casio880.com/programas_880/Estructuras/BARRAS.FX -O Estructuras/BARRAS.FX
wget https://www.casio880.com/programas_880/Estructuras/CROSS.FX -O Estructuras/CROSS.FX
wget https://www.casio880.com/programas_880/Estructuras/CROSS2.FX -O Estructuras/CROSS2.FX
wget https://www.casio880.com/programas_880/Estructuras/E-ISOSTA.FX -O Estructuras/E-ISOSTA.FX
wget https://www.casio880.com/programas_880/Estructuras/EMPARRIL.FX -O Estructuras/EMPARRIL.FX
wget https://www.casio880.com/programas_880/Estructuras/ESTR-ART.FX -O Estructuras/ESTR-ART.FX
wget https://www.casio880.com/programas_880/Estructuras/ESTR-GEN.FX -O Estructuras/ESTR-GEN.FX
wget https://www.casio880.com/programas_880/Estructuras/ESTR-INT.FX -O Estructuras/ESTR-INT.FX
wget https://www.casio880.com/programas_880/Estructuras/ESTR-ISO.FX -O Estructuras/ESTR-ISO.FX
wget https://www.casio880.com/programas_880/Estructuras/ESTR-PLA.FX -O Estructuras/ESTR-PLA.FX
wget https://www.casio880.com/programas_880/Estructuras/ESTRUC.FX -O Estructuras/ESTRUC.FX
wget https://www.casio880.com/programas_880/Estructuras/ESTRUCTU.FX -O Estructuras/ESTRUCTU.FX
wget https://www.casio880.com/programas_880/Estructuras/GENERALE.FX -O Estructuras/GENERALE.FX
wget https://www.casio880.com/programas_880/Estructuras/HIPERES.FX -O Estructuras/HIPERES.FX
wget https://www.casio880.com/programas_880/Estructuras/HIPER-IS.FX -O Estructuras/HIPER-IS.FX
wget https://www.casio880.com/programas_880/Estructuras/ISOSTATI.FX -O Estructuras/ISOSTATI.FX
wget https://www.casio880.com/programas_880/Estructuras/KLOCAL-G.FX -O Estructuras/KLOCAL-G.FX
wget https://www.casio880.com/programas_880/Estructuras/MANDRILE.FX -O Estructuras/MANDRILE.FX
wget https://www.casio880.com/programas_880/Estructuras/MATRICIA.FX -O Estructuras/MATRICIA.FX
wget https://www.casio880.com/programas_880/Estructuras/M-EQUILI.FX -O Estructuras/M-EQUILI.FX
wget https://www.casio880.com/programas_880/Estructuras/M-RIGI2.FX -O Estructuras/M-RIGI2.FX
wget https://www.casio880.com/programas_880/Estructuras/M-RIGID2.FX -O Estructuras/M-RIGID2.FX
wget https://www.casio880.com/programas_880/Estructuras/M-RIGIDE.FX -O Estructuras/M-RIGIDE.FX
wget https://www.casio880.com/programas_880/Estructuras/NUDOS.FX -O Estructuras/NUDOS.FX
wget https://www.casio880.com/programas_880/Estructuras/NUDOS2.FX -O Estructuras/NUDOS2.FX
wget https://www.casio880.com/programas_880/Estructuras/NUDOS-ES.FX -O Estructuras/NUDOS-ES.FX
wget https://www.casio880.com/programas_880/Estructuras/NUD-RIGI.FX -O Estructuras/NUD-RIGI.FX
wget https://www.casio880.com/programas_880/Estructuras/PORTI1.FX -O Estructuras/PORTI1.FX
wget https://www.casio880.com/programas_880/Estructuras/PORTICOS.FX -O Estructuras/PORTICOS.FX
wget https://www.casio880.com/programas_880/Estructuras/Pandeo Pilares Metálicos Según CTE DB SE A.doc -O Estructuras/Pandeo Pilares Metálicos Según CTE DB SE A.doc
wget https://www.casio880.com/programas_880/fisica/VECTORES.FX -O fisica/VECTORES.FX
wget https://www.casio880.com/programas_880/fisica/ERROR.FX -O fisica/ERROR.FX
wget https://www.casio880.com/programas_880/fisica/GRIM.FX -O fisica/GRIM.FX
wget https://www.casio880.com/programas_880/fisica/INERCIA2.FX -O fisica/INERCIA2.FX
wget https://www.casio880.com/programas_880/fisica/MAYWAY0.FX -O fisica/MAYWAY0.FX
wget https://www.casio880.com/programas_880/fisica/MOMENTOO.FX -O fisica/MOMENTOO.FX
wget https://www.casio880.com/programas_880/fisica/SUPCOORD.FX -O fisica/SUPCOORD.FX
wget https://www.casio880.com/programas_880/fisica/SUPERFIC.FX -O fisica/SUPERFIC.FX
wget https://www.casio880.com/programas_880/fisica/VECTOR.FX -O fisica/VECTOR.FX
wget https://www.casio880.com/programas_880/hidraulica/REMANSN.FX -O hidraulica/REMANSN.FX
wget https://www.casio880.com/programas_880/hidraulica/ARIETE.FX -O hidraulica/ARIETE.FX
wget https://www.casio880.com/programas_880/hidraulica/CALADO.FX -O hidraulica/CALADO.FX
wget https://www.casio880.com/programas_880/hidraulica/CANALESN.FX -O hidraulica/CANALESN.FX
wget https://www.casio880.com/programas_880/hidraulica/CHIMENEA.FX -O hidraulica/CHIMENEA.FX
wget https://www.casio880.com/programas_880/hidraulica/COEF-POL.FX -O hidraulica/COEF-POL.FX
wget https://www.casio880.com/programas_880/hidraulica/COLE850.FX -O hidraulica/COLE850.FX
wget https://www.casio880.com/programas_880/hidraulica/COLEBROO.FX -O hidraulica/COLEBROO.FX
wget https://www.casio880.com/programas_880/hidraulica/COLE-DAR.FX -O hidraulica/COLE-DAR.FX
wget https://www.casio880.com/programas_880/hidraulica/COLIF100.FX -O hidraulica/COLIF100.FX
wget https://www.casio880.com/programas_880/hidraulica/DEP-NUDO.FX -O hidraulica/DEP-NUDO.FX
wget https://www.casio880.com/programas_880/hidraulica/EMI.FX -O hidraulica/EMI.FX
wget https://www.casio880.com/programas_880/hidraulica/EMIS1000.FX -O hidraulica/EMIS1000.FX
wget https://www.casio880.com/programas_880/hidraulica/EMISARIO.FX -O hidraulica/EMISARIO.FX
wget https://www.casio880.com/programas_880/hidraulica/HIDDMV.FX -O hidraulica/HIDDMV.FX
wget https://www.casio880.com/programas_880/hidraulica/HIDRAULI.FX -O hidraulica/HIDRAULI.FX
wget https://www.casio880.com/programas_880/hidraulica/KIDD.FX -O hidraulica/KIDD.FX
wget https://www.casio880.com/programas_880/hidraulica/MANIN.FX -O hidraulica/MANIN.FX
wget https://www.casio880.com/programas_880/hidraulica/MEGAHID.FX -O hidraulica/MEGAHID.FX
wget https://www.casio880.com/programas_880/hidraulica/OSCIMAS.FX -O hidraulica/OSCIMAS.FX
wget https://www.casio880.com/programas_880/hidraulica/P0.FX -O hidraulica/P0.FX
wget https://www.casio880.com/programas_880/hidraulica/P3.FX -O hidraulica/P3.FX
wget https://www.casio880.com/programas_880/hidraulica/P9.FX -O hidraulica/P9.FX
wget https://www.casio880.com/programas_880/hidraulica/PLUVIALE.FX -O hidraulica/PLUVIALE.FX
wget https://www.casio880.com/programas_880/HormigOn/PRETENS.FX -O HormigOn/PRETENS.FX
wget https://www.casio880.com/programas_880/HormigOn/CARSMEC.FX -O HormigOn/CARSMEC.FX
wget https://www.casio880.com/programas_880/HormigOn/DEFOR.FX -O HormigOn/DEFOR.FX
wget https://www.casio880.com/programas_880/HormigOn/FLECTORE.FX -O HormigOn/FLECTORE.FX
wget https://www.casio880.com/programas_880/HormigOn/F-PARALE.FX -O HormigOn/F-PARALE.FX
wget https://www.casio880.com/programas_880/HormigOn/HORM-1.FX -O HormigOn/HORM-1.FX
wget https://www.casio880.com/programas_880/HormigOn/HORM-2.FX -O HormigOn/HORM-2.FX
wget https://www.casio880.com/programas_880/HormigOn/HORM-3.FX -O HormigOn/HORM-3.FX
wget https://www.casio880.com/programas_880/HormigOn/HORM-4.FX -O HormigOn/HORM-4.FX
wget https://www.casio880.com/programas_880/HormigOn/HORM-5.FX -O HormigOn/HORM-5.FX
wget https://www.casio880.com/programas_880/HormigOn/HORM-6.FX -O HormigOn/HORM-6.FX
wget https://www.casio880.com/programas_880/HormigOn/HORM-7.FX -O HormigOn/HORM-7.FX
wget https://www.casio880.com/programas_880/HormigOn/MAGNEL.FX -O HormigOn/MAGNEL.FX
wget https://www.casio880.com/programas_880/HormigOn/PER-ELAS.FX -O HormigOn/PER-ELAS.FX
wget https://www.casio880.com/programas_880/juegos/TRESRAYA.FX -O juegos/TRESRAYA.FX
wget https://www.casio880.com/programas_880/juegos/AHORCADO.FX -O juegos/AHORCADO.FX
wget https://www.casio880.com/programas_880/juegos/ANIMACIO.FX -O juegos/ANIMACIO.FX
wget https://www.casio880.com/programas_880/juegos/BARQUITO.FX -O juegos/BARQUITO.FX
wget https://www.casio880.com/programas_880/juegos/CASTLE.FX -O juegos/CASTLE.FX
wget https://www.casio880.com/programas_880/juegos/DAMAS.FX -O juegos/DAMAS.FX
wget https://www.casio880.com/programas_880/juegos/TETRIS.FX -O juegos/TETRIS.FX
wget https://www.casio880.com/programas_880/juegos/AJEDREC.fx -O juegos/AJEDREC.fx
wget https://www.casio880.com/programas_880/juegos/Langoliers.bas -O juegos/Langoliers.bas
wget https://www.casio880.com/programas_880/juegos/Langoliers-Compacto.bas -O juegos/Langoliers-Compacto.bas
wget https://www.casio880.com/programas_880/juegos/Alfabetico.bas -O juegos/Alfabetico.bas
wget https://www.casio880.com/programas_880/juegos/Alfabetico-Compacto.bas -O juegos/Alfabetico-Compacto.bas
wget https://www.casio880.com/programas_880/metodos_numericos%20/INTERPOL.FX -O metodos_numericos/INTERPOL.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/INT-P-F.FX -O metodos_numericos/INT-P-F.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/ITERACIO.FX -O metodos_numericos/ITERACIO.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/JACOBI.FX -O metodos_numericos/JACOBI.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/KARNAUGH.FX -O metodos_numericos/KARNAUGH.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/LAGRANGE.FX -O metodos_numericos/LAGRANGE.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/M-AITKEN.FX -O metodos_numericos/M-AITKEN.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/M-BAIRST.FX -O metodos_numericos/M-BAIRST.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/M-BAITKE.FX -O metodos_numericos/M-BAITKE.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/M-CUADRA.FX -O metodos_numericos/M-CUADRA.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/MINCUA.FX -O metodos_numericos/MINCUA.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/MIN-CUAD.FX -O metodos_numericos/MIN-CUAD.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/MINICUAD.FX -O metodos_numericos/MINICUAD.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/M-NEWTON.FX -O metodos_numericos/M-NEWTON.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/SIMPLEX.FX -O metodos_numericos/SIMPLEX.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/WORKSHOP.FX -O metodos_numericos/WORKSHOP.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/AITKEN.FX -O metodos_numericos/AITKEN.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/ALGORNEV.FX -O metodos_numericos/ALGORNEV.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/BAIRSTO2.FX -O metodos_numericos/BAIRSTO2.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/B-R-R-F.FX -O metodos_numericos/B-R-R-F.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/CHOLESKY.FX -O metodos_numericos/CHOLESKY.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/CN-1.FX -O metodos_numericos/CN-1.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/COEF-AJU.FX -O metodos_numericos/COEF-AJU.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/COMBI-1.FX -O metodos_numericos/COMBI-1.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/COMPL-EC.FX -O metodos_numericos/COMPL-EC.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/COMPLEJO.FX -O metodos_numericos/COMPLEJO.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/CON-POLI.FX -O metodos_numericos/CON-POLI.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/CROUT.FX -O metodos_numericos/CROUT.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/DOS-FASE.FX -O metodos_numericos/DOS-FASE.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/ELE-FINI.FX -O metodos_numericos/ELE-FINI.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/FIJO.FX -O metodos_numericos/FIJO.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/GAUSS.FX -O metodos_numericos/GAUSS.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/GAUS-SEI.FX -O metodos_numericos/GAUS-SEI.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/GRAM-SMT.FX -O metodos_numericos/GRAM-SMT.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/HELMERT2.FX -O metodos_numericos/HELMERT2.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/HELMERT3.FX -O metodos_numericos/HELMERT3.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/HERMITE.FX -O metodos_numericos/HERMITE.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/HILL-MUR.FX -O metodos_numericos/HILL-MUR.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/INTERLAG.FX -O metodos_numericos/INTERLAG.FX
wget https://www.casio880.com/programas_880/metodos_numericos%20/INTERNEW.FX -O metodos_numericos/INTERNEW.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/PROYTXUL.FX -O Ordenacion_urbana/PROYTXUL.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/ACCESIBI.FX -O Ordenacion_urbana/ACCESIBI.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/ACC-LOC2.FX -O Ordenacion_urbana/ACC-LOC2.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/ALTERNA.FX -O Ordenacion_urbana/ALTERNA.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/DEMOGRAF.FX -O Ordenacion_urbana/DEMOGRAF.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/HIDRICQA.FX -O Ordenacion_urbana/HIDRICQA.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/IN-OUT.FX -O Ordenacion_urbana/IN-OUT.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/IN-OUTPU.FX -O Ordenacion_urbana/IN-OUTPU.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/LOCA-ESP.FX -O Ordenacion_urbana/LOCA-ESP.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/LOC-EQUI.FX -O Ordenacion_urbana/LOC-EQUI.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/LOCESPE.FX -O Ordenacion_urbana/LOCESPE.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/LOGIST.FX -O Ordenacion_urbana/LOGIST.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/LOGOS.FX -O Ordenacion_urbana/LOGOS.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/MIGRAC.FX -O Ordenacion_urbana/MIGRAC.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/MIGRTXUL.FX -O Ordenacion_urbana/MIGRTXUL.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/NELSON.FX -O Ordenacion_urbana/NELSON.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/ODR-1.FX -O Ordenacion_urbana/ODR-1.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/ODR-4.FX -O Ordenacion_urbana/ODR-4.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/ODR-5.FX -O Ordenacion_urbana/ODR-5.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/ODR-6.FX -O Ordenacion_urbana/ODR-6.FX
wget https://www.casio880.com/programas_880/Ordenacion_urbana%20/PAISAJE.FX -O Ordenacion_urbana/PAISAJE.FX
wget https://www.casio880.com/programas_880/quimica/FORMULAR.FX -O quimica/FORMULAR.FX
wget https://www.casio880.com/programas_880/resistencia_materiales%20/TENMAX.FX -O resistencia_materiales/TENMAX.FX
wget https://www.casio880.com/programas_880/resistencia_materiales%20/FLEXI.FX -O resistencia_materiales/FLEXI.FX
wget https://www.casio880.com/programas_880/resistencia_materiales%20/REACTION.FX -O resistencia_materiales/REACTION.FX
wget https://www.casio880.com/programas_880/resistencia_materiales%20/ROTURA.FX -O resistencia_materiales/ROTURA.FX
wget https://www.casio880.com/programas_880/topografia/ACIDIS.FX -O topografia/ACIDIS.FX
wget https://www.casio880.com/programas_880/topografia/DISTAN.FX -O topografia/DISTAN.FX
wget https://www.casio880.com/programas_880/topografia/REPLANT.FX -O topografia/REPLANT.FX
wget https://www.casio880.com/programas_880/topografia/REPLANTE.FX -O topografia/REPLANTE.FX
wget https://www.casio880.com/programas_880/topografia/RES-TRI.FX -O topografia/RES-TRI.FX
wget https://www.casio880.com/programas_880/topografia/TERATOPO.FX -O topografia/TERATOPO.FX
wget https://www.casio880.com/programas_880/topografia/T-O-P-A-L-F-.zip -O topografia/T-O-P-A-L-F-.zip
wget https://www.casio880.com/programas_880/topografia/TOPDMV.FX -O topografia/TOPDMV.FX
wget https://www.casio880.com/programas_880/topografia/TRIANG1.FX -O topografia/TRIANG1.FX
wget https://www.casio880.com/programas_880/topografia/VARCOV3.FX -O topografia/VARCOV3.FX
wget https://www.casio880.com/programas_880/topografia/ANTONIO1.FX -O topografia/ANTONIO1.FX
wget https://www.casio880.com/programas_880/topografia/BASES.FX -O topografia/BASES.FX
wget https://www.casio880.com/programas_880/topografia/CARTOGRA.FX -O topografia/CARTOGRA.FX
wget https://www.casio880.com/programas_880/topografia/CLOTOI1.FX -O topografia/CLOTOI1.FX
wget https://www.casio880.com/programas_880/topografia/CLOTOI3.FX -O topografia/CLOTOI3.FX
wget https://www.casio880.com/programas_880/topografia/DIFTAB.FX -O topografia/DIFTAB.FX
wget https://www.casio880.com/programas_880/topografia/DIFTAB2.FX -O topografia/DIFTAB2.FX
wget https://www.casio880.com/programas_880/topografia/FOTOFRA.FX -O topografia/FOTOFRA.FX
wget https://www.casio880.com/programas_880/topografia/FOTOG2.FX -O topografia/FOTOG2.FX
wget https://www.casio880.com/programas_880/topografia/FOTOGRAM.FX -O topografia/FOTOGRAM.FX
wget https://www.casio880.com/programas_880/topografia/GIGATOPO.FX -O topografia/GIGATOPO.FX
wget https://www.casio880.com/programas_880/topografia/HANSEN.FX -O topografia/HANSEN.FX
wget https://www.casio880.com/programas_880/topografia/HELMERT.FX -O topografia/HELMERT.FX
wget https://www.casio880.com/programas_880/topografia/INTERSEC.FX -O topografia/INTERSEC.FX
wget https://www.casio880.com/programas_880/topografia/INT-INVE.FX -O topografia/INT-INVE.FX
wget https://www.casio880.com/programas_880/topografia/MA-VA-CO.FX -O topografia/MA-VA-CO.FX
wget https://www.casio880.com/programas_880/topografia/MAYWAY4.FX -O topografia/MAYWAY4.FX
wget https://www.casio880.com/programas_880/topografia/METOTOP.FX -O topografia/METOTOP.FX
wget https://www.casio880.com/programas_880/topografia/NIVELACI.FX -O topografia/NIVELACI.FX
wget https://www.casio880.com/programas_880/topografia/NIVTRI.FX -O topografia/NIVTRI.FX
wget https://www.casio880.com/programas_880/topografia/OBSERV.FX -O topografia/OBSERV.FX
wget https://www.casio880.com/programas_880/topografia/PILARTOP.FX -O topografia/PILARTOP.FX
wget https://www.casio880.com/programas_880/topografia/RE-CLO.FX -O topografia/RE-CLO.FX
wget https://www.casio880.com/programas_880/topografia/REDBASE.FX -O topografia/REDBASE.FX
wget https://www.casio880.com/programas_880/topografia/Geodesia.fx -O topografia/Geodesia.fx
wget https://www.casio880.com/programas_880/topografia/calplani.fx -O topografia/calplani.fx
wget https://www.casio880.com/programas_880/topografia/Mix2.bas -O topografia/Mix2.bas
wget https://www.casio880.com/programas_880/topografia/Trh.bas -O topografia/Trh.bas
wget https://www.casio880.com/programas_880/topografia/MT_BASE_6.fx -O topografia/MT_BASE_6.fx
wget https://www.casio880.com/programas_880/urbanismo/INCOGNIT.FX -O urbanismo/INCOGNIT.FX
wget https://www.casio880.com/programas_880/urbanismo/APROVECH.FX -O urbanismo/APROVECH.FX
wget https://www.casio880.com/programas_880/varios/INFORMAC.FX -O varios/INFORMAC.FX
wget https://www.casio880.com/programas_880/varios/LIBRTOP9.FX -O varios/LIBRTOP9.FX
wget https://www.casio880.com/programas_880/varios/MENSAJE.FX -O varios/MENSAJE.FX
wget https://www.casio880.com/programas_880/varios/OCULTAR.FX -O varios/OCULTAR.FX
wget https://www.casio880.com/programas_880/varios/ALFAORD.FX -O varios/ALFAORD.FX
wget https://www.casio880.com/programas_880/varios/CIRCPORC.FX -O varios/CIRCPORC.FX
wget https://www.casio880.com/programas_880/varios/CRONO.FX -O varios/CRONO.FX
wget https://www.casio880.com/programas_880/varios/ERROR.FX -O varios/ERROR.FX
wget https://www.casio880.com/programas_880/varios/HORAS.FX -O varios/HORAS.FX
